In [61]:
import pandas as pd

data = pd.read_excel('../data/service-data.xlsx')

In [62]:
data.head(2)

,Invoice Date,Job Card Date,Business Partner Name,Vehicle No.,Vehicle Model,Current KM Reading,INVOICE LINE TEXT
0,2017-05-30,2017-05-30,shivXXXXXXXXXX,KA03MFXXXX,BAJAJ AVENGER STREET 220,50000.0,ENGINE OIL
1,2017-06-02,2017-05-31,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758.0,ENGINE OIL

In [63]:
data.dropna(inplace=True)

In [64]:
import datetime

datetime.datetime.strptime('2017-05-30', '%Y-%m-%d')

datetime.datetime(2017, 5, 30, 0, 0)

In [65]:
data.index = data['Invoice Date'].apply(lambda x: datetime.datetime.strptime(f'{x.year}-{x.month}', '%Y-%m'))

In [66]:
data['Invoice Date'].value_counts()

2018-12-01    179
2018-12-04    167
2018-11-30    148
2018-11-05    136
2018-09-05    133
2018-10-06    131
2018-10-16    128
2018-11-27    123
2017-06-10    121
2018-09-04    119
2018-10-02    117
2018-12-15    113
2018-08-21    113
2018-12-22    113
2018-09-29    112
2018-12-24    111
2018-11-24    111
2018-10-11    111
2018-09-22    110
2018-12-19    108
2017-06-14    107
2018-06-19    106
2018-11-17    103
2018-11-20    102
2017-10-12    101
2018-10-25    100
2018-09-11     99
2018-11-03     98
2018-04-16     97
2017-09-01     96
             ...
2017-06-11     14
2018-06-17     14
2018-01-23     13
2017-10-06     13
2018-08-09     13
2017-08-18     13
2018-11-23     12
2018-11-11     12
2017-10-24     12
2018-04-29     12
2018-07-28     11
2017-05-31     10
2018-01-26     10
2017-10-15     10
2018-01-29     10
2018-10-19      9
2017-12-01      9
2017-08-20      9
2018-06-12      8
2018-02-14      8
2017-07-05      8
2017-09-28      7
2018-01-25      7
2017-11-15      6
2018-11-18      5
2017-12-27      5
2018-01-15      5
2018-02-18      4
2017-07-09      1
2017-05-30      1
Name: Invoice Date, Length: 555, dtype: int64

In [67]:
data[data['Business Partner Name'] == 'VIRUXXXXXXXXXX']

,Invoice Date,Job Card Date,Business Partner Name,Vehicle No.,Vehicle Model,Current KM Reading,INVOICE LINE TEXT
Invoice Date,,,,,,,
2018-01-01,2018-01-11,2018-01-11,VIRUXXXXXXXXXX,KA11ELXXXX,BAJAJ AVENGER STREET 220,20000.0,ENGINE WORK

In [68]:
data.head()

,Invoice Date,Job Card Date,Business Partner Name,Vehicle No.,Vehicle Model,Current KM Reading,INVOICE LINE TEXT
Invoice Date,,,,,,,
2017-05-01,2017-05-30,2017-05-30,shivXXXXXXXXXX,KA03MFXXXX,BAJAJ AVENGER STREET 220,50000.0,ENGINE OIL
2017-06-01,2017-06-02,2017-05-31,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758.0,ENGINE OIL
2017-06-01,2017-06-02,2017-05-31,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758.0,POLISH
2017-06-01,2017-06-02,2017-05-31,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758.0,CONSUMABLES
2017-06-01,2017-06-02,2017-05-31,KIRAXXXXXXXXXX,KA53ESXXXX,BAJAJ PULSAR NS 200,758.0,COOLANT OIL

In [72]:
value_counts = data['Business Partner Name'].value_counts()

In [73]:
value_counts.to_dict()

{'venkXXXXXXXXXX': 424,
 'manjXXXXXXXXXX': 362,
 'prasXXXXXXXXXX': 328,
 'shivXXXXXXXXXX': 314,
 'chanXXXXXXXXXX': 312,
 'raviXXXXXXXXXX': 310,
 'santXXXXXXXXXX': 296,
 'hariXXXXXXXXXX': 282,
 'PRASXXXXXXXXXX': 251,
 'arunXXXXXXXXXX': 242,
 'srinXXXXXXXXXX': 234,
 'mohaXXXXXXXXXX': 226,
 'vijaXXXXXXXXXX': 201,
 'abhiXXXXXXXXXX': 200,
 'rameXXXXXXXXXX': 199,
 'jayaXXXXXXXXXX': 197,
 'pravXXXXXXXXXX': 187,
 'balaXXXXXXXXXX': 176,
 'naveXXXXXXXXXX': 173,
 'sureXXXXXXXXXX': 171,
 'deepXXXXXXXXXX': 166,
 'rajeXXXXXXXXXX': 165,
 'sathXXXXXXXXXX': 161,
 'anilXXXXXXXXXX': 161,
 'vinoXXXXXXXXXX': 153,
 'ramaXXXXXXXXXX': 150,
 'MANJXXXXXXXXXX': 149,
 'dineXXXXXXXXXX': 146,
 'VENKXXXXXXXXXX': 144,
 'kartXXXXXXXXXX': 142,
 'SUREXXXXXXXXXX': 136,
 'giriXXXXXXXXXX': 135,
 'maheXXXXXXXXXX': 135,
 'raghXXXXXXXXXX': 133,
 'kishXXXXXXXXXX': 132,
 'pradXXXXXXXXXX': 131,
 'ashiXXXXXXXXXX': 131,
 'srikXXXXXXXXXX': 131,
 'naraXXXXXXXXXX': 124,
 'prakXXXXXXXXXX': 124,
 'sudhXXXXXXXXXX': 124,
 'ashoXXXXXXXXXX': 122,
 'bharXXXXXXXXXX': 121,
 'guruXXXXXXXXXX': 119,
 'HARIXXXXXXXXXX': 118,
 'madhXXXXXXXXXX': 115,
 'muraXXXXXXXXXX': 110,
 'gopiXXXXXXXXXX': 110,
 'krisXXXXXXXXXX': 107,
 'nageXXXXXXXXXX': 107,
 'NAVEXXXXXXXXXX': 106,
 'rakeXXXXXXXXXX': 104,
 'ANILXXXXXXXXXX': 103,
 'sumiXXXXXXXXXX': 102,
 'kumaXXXXXXXXXX': 102,
 'nareXXXXXXXXXX': 99,
 'ananXXXXXXXXXX': 99,
 'maniXXXXXXXXXX': 98,
 'sridXXXXXXXXXX': 97,
 'vinaXXXXXXXXXX': 96,
 'lokeXXXXXXXXXX': 95,
 'sachXXXXXXXXXX': 95,
 'laksXXXXXXXXXX': 91,
 'amitXXXXXXXXXX': 91,
 'KIRAXXXXXXXXXX': 90,
 'suniXXXXXXXXXX': 89,
 'avinXXXXXXXXXX': 89,
 'ganeXXXXXXXXXX': 88,
 'shasXXXXXXXXXX': 88,
 'kiraXXXXXXXXXX': 87,
 'shanXXXXXXXXXX': 87,
 'basaXXXXXXXXXX': 84,
 'pratXXXXXXXXXX': 84,
 'rajuXXXXXXXXXX': 83,
 'vishXXXXXXXXXX': 83,
 'MADHXXXXXXXXXX': 82,
 'puniXXXXXXXXXX': 82,
 'jagaXXXXXXXXXX': 82,
 'RAJUXXXXXXXXXX': 82,
 'somaXXXXXXXXXX': 81,
 'SANTXXXXXXXXXX': 81,
 'DEEPXXXXXXXXXX': 78,
 'rahuXXXXXXXXXX': 78,
 'nagrXXXXXXXXXX': 78,
 'saurXXXXXXXXXX': 78,
 'dharXXXXXXXXXX': 77,
 'rajaXXXXXXXXXX': 77,
 'devaXXXXXXXXXX': 75,
 'pavaXXXXXXXXXX': 75,
 'johnXXXXXXXXXX': 74,
 'gangXXXXXXXXXX': 74,
 'sanjXXXXXXXXXX': 71,
 'VEERXXXXXXXXXX': 69,
 'ABHIXXXXXXXXXX': 69,
 'chenXXXXXXXXXX': 69,
 'ANANXXXXXXXXXX': 68,
 'aditXXXXXXXXXX': 68,
 'prabXXXXXXXXXX': 68,
 'MAHEXXXXXXXXXX': 67,
 'ROHIXXXXXXXXXX': 66,
 'akshXXXXXXXXXX': 66,
 'ayusXXXXXXXXXX': 65,
 'muniXXXXXXXXXX': 64,
 'rohiXXXXXXXXXX': 63,
 'ajayXXXXXXXXXX': 62,
 'yogeXXXXXXXXXX': 62,
 'raj XXXXXXXXXX': 61,
 'LAKSXXXXXXXXXX': 61,
 'aravXXXXXXXXXX': 59,
 'mbs XXXXXXXXXX': 59,
 'KRISXXXXXXXXXX': 59,
 'kundXXXXXXXXXX': 59,
 'radhXXXXXXXXXX': 59,
 'vamsXXXXXXXXXX': 59,
 'dhanXXXXXXXXXX': 58,
 'ajitXXXXXXXXXX': 58,
 'BHARXXXXXXXXXX': 57,
 'SHIVXXXXXXXXXX': 57,
 'ashwXXXXXXXXXX': 57,
 'ramXXXXXXXXXX': 56,
 'chaiXXXXXXXXXX': 56,
 'yelaXXXXXXXXXX': 55,
 'akasXXXXXXXXXX': 54,
 'nilmXXXXXXXXXX': 54,
 'subrXXXXXXXXXX': 54,
 'sivaXXXXXXXXXX': 54,
 'nithXXXXXXXXXX': 54,
 'shyaXXXXXXXXXX': 53,
 'viveXXXXXXXXXX': 52,
 'PRABXXXXXXXXXX': 52,
 'sandXXXXXXXXXX': 51,
 'arviXXXXXXXXXX': 50,
 'brijXXXXXXXXXX': 50,
 'rajkXXXXXXXXXX': 49,
 'RAMAXXXXXXXXXX': 49,
 'rishXXXXXXXXXX': 49,
 'pathXXXXXXXXXX': 49,
 'tapaXXXXXXXXXX': 48,
 'anurXXXXXXXXXX': 47,
 'hemaXXXXXXXXXX': 47,
 'kilaXXXXXXXXXX': 46,
 'BALAXXXXXXXXXX': 46,
 'mithXXXXXXXXXX': 46,
 'AMOLXXXXXXXXXX': 46,
 'VISHXXXXXXXXXX': 45,
 'manoXXXXXXXXXX': 45,
 'shubXXXXXXXXXX': 45,
 'bhasXXXXXXXXXX': 45,
 'MALLXXXXXXXXXX': 44,
 'veluXXXXXXXXXX': 44,
 'muthXXXXXXXXXX': 44,
 'sai XXXXXXXXXX': 44,
 'MAYAXXXXXXXXXX': 44,
 'aliXXXXXXXXXX': 44,
 'poliXXXXXXXXXX': 44,
 'chetXXXXXXXXXX': 44,
 'janaXXXXXXXXXX': 44,
 'bikaXXXXXXXXXX': 43,
 'sujiXXXXXXXXXX': 43,
 'niraXXXXXXXXXX': 43,
 'sameXXXXXXXXXX': 43,
 'niveXXXXXXXXXX': 43,
 'MITHXXXXXXXXXX': 43,
 'satiXXXXXXXXXX': 43,
 'KARAXXXXXXXXXX': 42,
 'subhXXXXXXXXXX': 42,
 'RANJXXXXXXXXXX': 42,
 'GIRIXXXXXXXXXX': 42,
 'PRAKXXXXXXXXXX': 41,
 'ankiXXXXXXXXXX': 41,
 'rangXXXXXXXXXX': 41,
 'mahaXXXXXXXXXX': 41,
 'nagaXXXXXXXXXX': 40,
 'SUNIXXXXXXXXXX': 40,
 'harsXXXXXXXXXX': 40,
 'VINAXXXXXXXXXX': 39,
 'RAGHXXXXXXXXXX': 39,
 'suryXXXXXXXXXX': 39,
 'pramXXXXXXXXXX': 39,
 'MUNIXXXXXXXXXX': 39,
 'GYANXXXXXXXXXX': 38,
 'sharXXXXXXXXXX': 38,
 'sahiXXXXXXXXXX': 38,
 'CHETXXXXXXXXXX': 38,
 'n prXXXXXXXXXX': 38,
 'VINEXXXXXXXXXX': 37,
 'prutXXXXXXXXXX': 37,
 'arulXXXXXXXXXX': 37,
 'KALYXXXXXXXXXX': 37,
 'sudeXXXXXXXXXX': 37,
 'PANKXXXXXXXXXX': 37,
 'VIJAXXXXXXXXXX': 37,
 'CHANXXXXXXXXXX': 36,
 'nateXXXXXXXXXX': 36,
 'athaXXXXXXXXXX': 36,
 'SUMIXXXXXXXXXX': 36,
 'ASHUXXXXXXXXXX': 35,
 'shriXXXXXXXXXX': 35,
 'jeevXXXXXXXXXX': 35,
 'kapiXXXXXXXXXX': 35,
 'tharXXXXXXXXXX': 35,
 'AVINXXXXXXXXXX': 35,
 'gaurXXXXXXXXXX': 35,
 'anisXXXXXXXXXX': 35,
 'tanmXXXXXXXXXX': 34,
 'gourXXXXXXXXXX': 34,
 'NAGEXXXXXXXXXX': 34,
 'piyeXXXXXXXXXX': 34,
 'm gaXXXXXXXXXX': 34,
 'j siXXXXXXXXXX': 34,
 'reetXXXXXXXXXX': 33,
 'SATHXXXXXXXXXX': 33,
 'gokuXXXXXXXXXX': 32,
 'nasfXXXXXXXXXX': 32,
 'adesXXXXXXXXXX': 32,
 'mukeXXXXXXXXXX': 32,
 'anupXXXXXXXXXX': 32,
 'MANOXXXXXXXXXX': 32,
 'srivXXXXXXXXXX': 32,
 'sajjXXXXXXXXXX': 32,
 'debaXXXXXXXXXX': 32,
 'apurXXXXXXXXXX': 32,
 'sumeXXXXXXXXXX': 31,
 'prajXXXXXXXXXX': 31,
 'ULLAXXXXXXXXXX': 31,
 'AMITXXXXXXXXXX': 31,
 'vikrXXXXXXXXXX': 31,
 'punkXXXXXXXXXX': 31,
 'NARAXXXXXXXXXX': 31,
 'LATHXXXXXXXXXX': 30,
 'KALLXXXXXXXXXX': 30,
 'veerXXXXXXXXXX': 30,
 'shekXXXXXXXXXX': 30,
 'peteXXXXXXXXXX': 30,
 'syedXXXXXXXXXX': 30,
 'bramXXXXXXXXXX': 30,
 'RAJKXXXXXXXXXX': 30,
 'ALOKXXXXXXXXXX': 30,
 'BASAXXXXXXXXXX': 29,
 'mayaXXXXXXXXXX': 29,
 'robiXXXXXXXXXX': 29,
 'GAUTXXXXXXXXXX': 29,
 'vineXXXXXXXXXX': 29,
 'pranXXXXXXXXXX': 29,
 'mahiXXXXXXXXXX': 29,
 'RAMEXXXXXXXXXX': 29,
 'brajXXXXXXXXXX': 29,
 'GAURXXXXXXXXXX': 29,
 'ragaXXXXXXXXXX': 29,
 'uma XXXXXXXXXX': 29,
 'SATIXXXXXXXXXX': 29,
 'UMESXXXXXXXXXX': 29,
 'jayeXXXXXXXXXX': 28,
 'TAMIXXXXXXXXXX': 28,
 'c moXXXXXXXXXX': 28,
 'bubaXXXXXXXXXX': 28,
 'digeXXXXXXXXXX': 28,
 'martXXXXXXXXXX': 28,
 'babuXXXXXXXXXX': 28,
 'ADITXXXXXXXXXX': 28,
 'SARVXXXXXXXXXX': 28,
 'suraXXXXXXXXXX': 28,
 'GLENXXXXXXXXXX': 28,
 'konaXXXXXXXXXX': 27,
 'sudaXXXXXXXXXX': 27,
 'SUDHXXXXXXXXXX': 27,
 'gowrXXXXXXXXXX': 27,
 'sadhXXXXXXXXXX': 27,
 'GANEXXXXXXXXXX': 27,
 'RIYAXXXXXXXXXX': 27,
 'sonuXXXXXXXXXX': 27,
 'ishaXXXXXXXXXX': 27,
 'moulXXXXXXXXXX': 27,
 'ARUNXXXXXXXXXX': 27,
 'RAVIXXXXXXXXXX': 27,
 'arjuXXXXXXXXXX': 26,
 'BABUXXXXXXXXXX': 26,
 'paraXXXXXXXXXX': 26,
 'TANGXXXXXXXXXX': 26,
 'sagaXXXXXXXXXX': 26,
 'ankuXXXXXXXXXX': 26,
 'chinXXXXXXXXXX': 25,
 'SHUBXXXXXXXXXX': 25,
 'reddXXXXXXXXXX': 25,
 'VIVEXXXXXXXXXX': 25,
 'MURAXXXXXXXXXX': 25,
 'puruXXXXXXXXXX': 25,
 'RENUXXXXXXXXXX': 25,
 'SANJXXXXXXXXXX': 25,
 'RAHUXXXXXXXXXX': 25,
 'satyXXXXXXXXXX': 25,
 'varuXXXXXXXXXX': 25,
 'RAJEXXXXXXXXXX': 25,
 'umesXXXXXXXXXX': 25,
 'hendXXXXXXXXXX': 24,
 'charXXXXXXXXXX': 24,
 'ANJAXXXXXXXXXX': 24,
 'deviXXXXXXXXXX': 24,
 'jhanXXXXXXXXXX': 24,
 'ASHOXXXXXXXXXX': 24,
 'NITIXXXXXXXXXX': 24,
 'tumiXXXXXXXXXX': 24,
 'HariXXXXXXXXXX': 24,
 'yugaXXXXXXXXXX': 23,
 'kajaXXXXXXXXXX': 23,
 'wasiXXXXXXXXXX': 23,
 'SHASXXXXXXXXXX': 23,
 'ARBIXXXXXXXXXX': 23,
 'amarXXXXXXXXXX': 23,
 'muleXXXXXXXXXX': 23,
 'munrXXXXXXXXXX': 23,
 'rajgXXXXXXXXXX': 23,
 'hanuXXXXXXXXXX': 23,
 'aswiXXXXXXXXXX': 23,
 'SIVRXXXXXXXXXX': 23,
 'PREAXXXXXXXXXX': 23,
 'ANOOXXXXXXXXXX': 23,
 'A VEXXXXXXXXXX': 22,
 'thanXXXXXXXXXX': 22,
 'JOHNXXXXXXXXXX': 22,
 'purvXXXXXXXXXX': 22,
 'anjiXXXXXXXXXX': 22,
 'B naXXXXXXXXXX': 22,
 'RONAXXXXXXXXXX': 22,
 'arumXXXXXXXXXX': 22,
 'KHANXXXXXXXXXX': 22,
 'ezhiXXXXXXXXXX': 22,
 'thirXXXXXXXXXX': 22,
 'maliXXXXXXXXXX': 22,
 'tippXXXXXXXXXX': 22,
 't r XXXXXXXXXX': 22,
 'ADIVXXXXXXXXXX': 22,
 'sulaXXXXXXXXXX': 22,
 'goutXXXXXXXXXX': 22,
 'PARTXXXXXXXXXX': 22,
 'patrXXXXXXXXXX': 22,
 'PANDXXXXXXXXXX': 22,
 'SETHXXXXXXXXXX': 22,
 'kotaXXXXXXXXXX': 21,
 'NAFIXXXXXXXXXX': 21,
 'swarXXXXXXXXXX': 21,
 'ramuXXXXXXXXXX': 21,
 'bodiXXXXXXXXXX': 21,
 'abisXXXXXXXXXX': 21,
 'aby XXXXXXXXXX': 21,
 'RAJXXXXXXXXXX': 21,
 'jai XXXXXXXXXX': 21,
 'tejaXXXXXXXXXX': 21,
 'renuXXXXXXXXXX': 21,
 'ranjXXXXXXXXXX': 21,
 'vikaXXXXXXXXXX': 21,
 'kushXXXXXXXXXX': 21,
 'raguXXXXXXXXXX': 21,
 'PAVAXXXXXXXXXX': 21,
 'nandXXXXXXXXXX': 21,
 'thipXXXXXXXXXX': 21,
 'HEMAXXXXXXXXXX': 21,
 'pankXXXXXXXXXX': 20,
 'stevXXXXXXXXXX': 20,
 'asjoXXXXXXXXXX': 20,
 'sadrXXXXXXXXXX': 20,
 'somnXXXXXXXXXX': 20,
 'neerXXXXXXXXXX': 20,
 'naniXXXXXXXXXX': 20,
 'sambXXXXXXXXXX': 20,
 'khajXXXXXXXXXX': 20,
 'yatiXXXXXXXXXX': 20,
 'ASWAXXXXXXXXXX': 20,
 'dvvnXXXXXXXXXX': 20,
 'jyotXXXXXXXXXX': 20,
 'appuXXXXXXXXXX': 20,
 'rambXXXXXXXXXX': 20,
 'lopaXXXXXXXXXX': 20,
 'A J XXXXXXXXXX': 20,
 'SELVXXXXXXXXXX': 20,
 'SAI XXXXXXXXXX': 20,
 'JIBUXXXXXXXXXX': 20,
 'B U XXXXXXXXXX': 20,
 'chirXXXXXXXXXX': 20,
 'kuppXXXXXXXXXX': 20,
 'joseXXXXXXXXXX': 19,
 'UDAYXXXXXXXXXX': 19,
 'sri XXXXXXXXXX': 19,
 'POLIXXXXXXXXXX': 19,
 'VASAXXXXXXXXXX': 19,
 'deraXXXXXXXXXX': 19,
 'SUBAXXXXXXXXXX': 19,
 'sarmXXXXXXXXXX': 19,
 'kesaXXXXXXXXXX': 19,
 'pothXXXXXXXXXX': 19,
 'PRATXXXXXXXXXX': 19,
 'birbXXXXXXXXXX': 19,
 'AJOSXXXXXXXXXX': 19,
 'NALLXXXXXXXXXX': 19,
 'VARUXXXXXXXXXX': 19,
 'p siXXXXXXXXXX': 19,
 'gowtXXXXXXXXXX': 18,
 'K daXXXXXXXXXX': 18,
 'yuvrXXXXXXXXXX': 18,
 'SANDXXXXXXXXXX': 18,
 'vimaXXXXXXXXXX': 18,
 'MohaXXXXXXXXXX': 18,
 'YOGAXXXXXXXXXX': 18,
 'DiliXXXXXXXXXX': 18,
 'vignXXXXXXXXXX': 18,
 'madaXXXXXXXXXX': 18,
 'AJAYXXXXXXXXXX': 18,
 'RUPEXXXXXXXXXX': 18,
 'a v XXXXXXXXXX': 18,
 'laxmXXXXXXXXXX': 18,
 'danaXXXXXXXXXX': 18,
 'ram XXXXXXXXXX': 18,
 'abjiXXXXXXXXXX': 18,
 'RAJAXXXXXXXXXX': 17,
 'niyaXXXXXXXXXX': 17,
 'SURYXXXXXXXXXX': 17,
 'hareXXXXXXXXXX': 17,
 'riyaXXXXXXXXXX': 17,
 'rijuXXXXXXXXXX': 17,
 'NATAXXXXXXXXXX': 17,
 'rajiXXXXXXXXXX': 17,
 'GURUXXXXXXXXXX': 17,
 'alokXXXXXXXXXX': 17,
 'baluXXXXXXXXXX': 17,
 'SIRAXXXXXXXXXX': 17,
 'jijeXXXXXXXXXX': 17,
 'sidhXXXXXXXXXX': 17,
 'S BAXXXXXXXXXX': 17,
 'rup XXXXXXXXXX': 17,
 'madeXXXXXXXXXX': 17,
 's n XXXXXXXXXX': 17,
 'abraXXXXXXXXXX': 17,
 'dibyXXXXXXXXXX': 17,
 'car XXXXXXXXXX': 17,
 'PRAVXXXXXXXXXX': 17,
 'srirXXXXXXXXXX': 17,
 'eshwXXXXXXXXXX': 17,
 'diliXXXXXXXXXX': 16,
 'visaXXXXXXXXXX': 16,
 'atmuXXXXXXXXXX': 16,
 'RAMXXXXXXXXXX': 16,
 'JEEVXXXXXXXXXX': 16,
 'kasiXXXXXXXXXX': 16,
 'MBS XXXXXXXXXX': 16,
 'DEDAXXXXXXXXXX': 16,
 'subiXXXXXXXXXX': 16,
 'VASUXXXXXXXXXX': 16,
 'rajsXXXXXXXXXX': 16,
 'chitXXXXXXXXXX': 16,
 'venuXXXXXXXXXX': 16,
 'viloXXXXXXXXXX': 16,
 'DAVIXXXXXXXXXX': 16,
 'deniXXXXXXXXXX': 16,
 'PRADXXXXXXXXXX': 16,
 'powlXXXXXXXXXX': 16,
 'MAHAXXXXXXXXXX': 16,
 'anooXXXXXXXXXX': 16,
 'mohiXXXXXXXXXX': 16,
 'SHARXXXXXXXXXX': 16,
 'LITOXXXXXXXXXX': 15,
 'devrXXXXXXXXXX': 15,
 'UJJWXXXXXXXXXX': 15,
 'abijXXXXXXXXXX': 15,
 'amulXXXXXXXXXX': 15,
 'jiteXXXXXXXXXX': 15,
 'ADHIXXXXXXXXXX': 15,
 'sabuXXXXXXXXXX': 15,
 'maruXXXXXXXXXX': 15,
 'BROJXXXXXXXXXX': 15,
 'ANKUXXXXXXXXXX': 15,
 'VINOXXXXXXXXXX': 15,
 'velaXXXXXXXXXX': 15,
 'MOHAXXXXXXXXXX': 15,
 'saraXXXXXXXXXX': 15,
 'JOGAXXXXXXXXXX': 15,
 'aneeXXXXXXXXXX': 15,
 'irapXXXXXXXXXX': 15,
 'utkaXXXXXXXXXX': 15,
 'himaXXXXXXXXXX': 15,
 'nihiXXXXXXXXXX': 15,
 'PREMXXXXXXXXXX': 15,
 'soumXXXXXXXXXX': 14,
 'RISHXXXXXXXXXX': 14,
 'KUSUXXXXXXXXXX': 14,
 'samaXXXXXXXXXX': 14,
 'PADMXXXXXXXXXX': 14,
 'sarvXXXXXXXXXX': 14,
 'sankXXXXXXXXXX': 14,
 'SAGAXXXXXXXXXX': 14,
 'VAIRXXXXXXXXXX': 14,
 'sateXXXXXXXXXX': 14,
 'bandXXXXXXXXXX': 14,
 'kangXXXXXXXXXX': 14,
 'sundXXXXXXXXXX': 14,
 'anjaXXXXXXXXXX': 14,
 'DANNXXXXXXXXXX': 14,
 'baraXXXXXXXXXX': 14,
 'ramlXXXXXXXXXX': 14,
 'SENTXXXXXXXXXX': 14,
 'pappXXXXXXXXXX': 14,
 'asifXXXXXXXXXX': 14,
 'KUMAXXXXXXXXXX': 14,
 'roopXXXXXXXXXX': 14,
 'ANSUXXXXXXXXXX': 14,
 'M GIXXXXXXXXXX': 14,
 'dhruXXXXXXXXXX': 14,
 'k k XXXXXXXXXX': 14,
 'muddXXXXXXXXXX': 14,
 'gaveXXXXXXXXXX': 14,
 'KISHXXXXXXXXXX': 14,
 'JAYAXXXXXXXXXX': 14,
 'dhivXXXXXXXXXX': 14,
 'bhuvXXXXXXXXXX': 14,
 'V SRXXXXXXXXXX': 14,
 'vireXXXXXXXXXX': 13,
 'piyuXXXXXXXXXX': 13,
 'ashuXXXXXXXXXX': 13,
 'g d XXXXXXXXXX': 13,
 'swagXXXXXXXXXX': 13,
 'PRAMXXXXXXXXXX': 13,
 'kailXXXXXXXXXX': 13,
 'THIRXXXXXXXXXX': 13,
 'mushXXXXXXXXXX': 13,
 'megaXXXXXXXXXX': 13,
 'K GUXXXXXXXXXX': 13,
 'RASHXXXXXXXXXX': 13,
 'pawaXXXXXXXXXX': 13,
 'VERAXXXXXXXXXX': 13,
 'JANAXXXXXXXXXX': 13,
 'ROSHXXXXXXXXXX': 13,
 'ansuXXXXXXXXXX': 13,
 'amruXXXXXXXXXX': 13,
 'SOUMXXXXXXXXXX': 13,
 'a naXXXXXXXXXX': 13,
 'sampXXXXXXXXXX': 13,
 'VINIXXXXXXXXXX': 13,
 'JoanXXXXXXXXXX': 13,
 'OBULXXXXXXXXXX': 13,
 'jennXXXXXXXXXX': 13,
 'manuXXXXXXXXXX': 13,
 'firdXXXXXXXXXX': 12,
 'gandXXXXXXXXXX': 12,
 'khusXXXXXXXXXX': 12,
 'VELUXXXXXXXXXX': 12,
 'BHAVXXXXXXXXXX': 12,
 'neemXXXXXXXXXX': 12,
 'raahXXXXXXXXXX': 12,
 'mansXXXXXXXXXX': 12,
 'PRITXXXXXXXXXX': 12,
 'D VIXXXXXXXXXX': 12,
 'mendXXXXXXXXXX': 12,
 'KARTXXXXXXXXXX': 12,
 'rizwXXXXXXXXXX': 12,
 'ANISXXXXXXXXXX': 12,
 'rataXXXXXXXXXX': 12,
 'RAKEXXXXXXXXXX': 12,
 'huzaXXXXXXXXXX': 12,
 'DHILXXXXXXXXXX': 12,
 'SUBHXXXXXXXXXX': 12,
 'gunaXXXXXXXXXX': 12,
 'NAGAXXXXXXXXXX': 12,
 'UPENXXXXXXXXXX': 12,
 'SHERXXXXXXXXXX': 12,
 'AYANXXXXXXXXXX': 12,
 'GANAXXXXXXXXXX': 12,
 'baruXXXXXXXXXX': 12,
 'SOMAXXXXXXXXXX': 12,
 'upenXXXXXXXXXX': 12,
 'sonoXXXXXXXXXX': 12,
 'naviXXXXXXXXXX': 12,
 'mariXXXXXXXXXX': 12,
 'rathXXXXXXXXXX': 12,
 'P naXXXXXXXXXX': 12,
 'anirXXXXXXXXXX': 12,
 'UPASXXXXXXXXXX': 12,
 'rupaXXXXXXXXXX': 12,
 'dheeXXXXXXXXXX': 12,
 'T s XXXXXXXXXX': 12,
 'SARAXXXXXXXXXX': 12,
 'c anXXXXXXXXXX': 12,
 'LINGXXXXXXXXXX': 12,
 'beniXXXXXXXXXX': 12,
 'partXXXXXXXXXX': 12,
 'rastXXXXXXXXXX': 12,
 'ABIRXXXXXXXXXX': 12,
 'hajaXXXXXXXXXX': 12,
 'RAMCXXXXXXXXXX': 12,
 'SAROXXXXXXXXXX': 12,
 'boyaXXXXXXXXXX': 12,
 'nikhXXXXXXXXXX': 12,
 'iliaXXXXXXXXXX': 12,
 'sibiXXXXXXXXXX': 11,
 'VijaXXXXXXXXXX': 11,
 'TEJAXXXXXXXXXX': 11,
 'sentXXXXXXXXXX': 11,
 'leslXXXXXXXXXX': 11,
 'SHALXXXXXXXXXX': 11,
 'PradXXXXXXXXXX': 11,
 'SRI XXXXXXXXXX': 11,
 'SHAKXXXXXXXXXX': 11,
 'DEVEXXXXXXXXXX': 11,
 'm siXXXXXXXXXX': 11,
 'SAMEXXXXXXXXXX': 11,
 'shakXXXXXXXXXX': 11,
 'aminXXXXXXXXXX': 11,
 'munnXXXXXXXXXX': 11,
 'G maXXXXXXXXXX': 11,
 'lingXXXXXXXXXX': 11,
 'shreXXXXXXXXXX': 11,
 'G SHXXXXXXXXXX': 11,
 'thyaXXXXXXXXXX': 11,
 'NITHXXXXXXXXXX': 11,
 'T GOXXXXXXXXXX': 11,
 'nishXXXXXXXXXX': 11,
 'razaXXXXXXXXXX': 11,
 'taruXXXXXXXXXX': 11,
 'S VIXXXXXXXXXX': 11,
 'PARMXXXXXXXXXX': 11,
 'rachXXXXXXXXXX': 11,
 'hanmXXXXXXXXXX': 11,
 'k paXXXXXXXXXX': 11,
 'biraXXXXXXXXXX': 11,
 'mallXXXXXXXXXX': 11,
 'TRIDXXXXXXXXXX': 11,
 'VIGNXXXXXXXXXX': 11,
 'sabiXXXXXXXXXX': 11,
 'akhiXXXXXXXXXX': 11,
 'SHAMXXXXXXXXXX': 11,
 'kavyXXXXXXXXXX': 11,
 'vasaXXXXXXXXXX': 11,
 'bhavXXXXXXXXXX': 11,
 'rajbXXXXXXXXXX': 11,
 'kiruXXXXXXXXXX': 11,
 'reniXXXXXXXXXX': 11,
 'VIBIXXXXXXXXXX': 11,
 'dasaXXXXXXXXXX': 11,
 'P N XXXXXXXXXX': 10,
 'mabiXXXXXXXXXX': 10,
 'yeshXXXXXXXXXX': 10,
 'sairXXXXXXXXXX': 10,
 'rochXXXXXXXXXX': 10,
 'ayyaXXXXXXXXXX': 10,
 'kar XXXXXXXXXX': 10,
 'OMKAXXXXXXXXXX': 10,
 'P veXXXXXXXXXX': 10,
 'K VEXXXXXXXXXX': 10,
 'NANDXXXXXXXXXX': 10,
 'shahXXXXXXXXXX': 10,
 'k p XXXXXXXXXX': 10,
 'deerXXXXXXXXXX': 10,
 'RITEXXXXXXXXXX': 10,
 'phalXXXXXXXXXX': 10,
 'archXXXXXXXXXX': 10,
 'viswXXXXXXXXXX': 10,
 'arghXXXXXXXXXX': 10,
 'unniXXXXXXXXXX': 10,
 'dileXXXXXXXXXX': 10,
 'lenjXXXXXXXXXX': 10,
 'lathXXXXXXXXXX': 10,
 'ahmaXXXXXXXXXX': 10,
 'swamXXXXXXXXXX': 10,
 'K N XXXXXXXXXX': 10,
 'sujeXXXXXXXXXX': 10,
 'sahuXXXXXXXXXX': 10,
 'divaXXXXXXXXXX': 10,
 'JAGAXXXXXXXXXX': 10,
 'damoXXXXXXXXXX': 10,
 'G saXXXXXXXXXX': 10,
 'anikXXXXXXXXXX': 10,
 'DONGXXXXXXXXXX': 10,
 'thagXXXXXXXXXX': 9,
 'SIDDXXXXXXXXXX': 9,
 'N R XXXXXXXXXX': 9,
 'arkaXXXXXXXXXX': 9,
 'gamoXXXXXXXXXX': 9,
 'SRINXXXXXXXXXX': 9,
 'arjiXXXXXXXXXX': 9,
 'VIKAXXXXXXXXXX': 9,
 'tukaXXXXXXXXXX': 9,
 'udayXXXXXXXXXX': 9,
 'taraXXXXXXXXXX': 9,
 'namcXXXXXXXXXX': 9,
 'paruXXXXXXXXXX': 9,
 'THOPXXXXXXXXXX': 9,
 'likiXXXXXXXXXX': 9,
 'sapnXXXXXXXXXX': 9,
 'sumaXXXXXXXXXX': 9,
 'shobXXXXXXXXXX': 9,
 'kamaXXXXXXXXXX': 9,
 'smarXXXXXXXXXX': 9,
 'RAGAXXXXXXXXXX': 9,
 'subaXXXXXXXXXX': 9,
 'nuthXXXXXXXXXX': 9,
 'ARVIXXXXXXXXXX': 9,
 'G V XXXXXXXXXX': 9,
 'anuXXXXXXXXXX': 9,
 'NANJXXXXXXXXXX': 9,
 'AnooXXXXXXXXXX': 9,
 'yathXXXXXXXXXX': 8,
 'muruXXXXXXXXXX': 8,
 'R GAXXXXXXXXXX': 8,
 'ABISXXXXXXXXXX': 8,
 'thayXXXXXXXXXX': 8,
 'georXXXXXXXXXX': 8,
 'vadiXXXXXXXXXX': 8,
 'B S XXXXXXXXXX': 8,
 'ahmeXXXXXXXXXX': 8,
 'diptXXXXXXXXXX': 8,
 't saXXXXXXXXXX': 8,
 'papuXXXXXXXXXX': 8,
 'gautXXXXXXXXXX': 8,
 'lukoXXXXXXXXXX': 8,
 'k reXXXXXXXXXX': 8,
 'daniXXXXXXXXXX': 8,
 'amanXXXXXXXXXX': 8,
 'JOANXXXXXXXXXX': 8,
 'irfaXXXXXXXXXX': 8,
 'saikXXXXXXXXXX': 8,
 'DRIMXXXXXXXXXX': 8,
 'DOLFXXXXXXXXXX': 8,
 'ROOPXXXXXXXXXX': 8,
 'EYLAXXXXXXXXXX': 8,
 'S V XXXXXXXXXX': 8,
 'sudiXXXXXXXXXX': 8,
 'byreXXXXXXXXXX': 8,
 'arbaXXXXXXXXXX': 8,
 'JAMEXXXXXXXXXX': 8,
 'azmaXXXXXXXXXX': 8,
 'CHINXXXXXXXXXX': 8,
 'DEVAXXXXXXXXXX': 8,
 'BHIMXXXXXXXXXX': 8,
 'keshXXXXXXXXXX': 7,
 'P raXXXXXXXXXX': 7,
 'ganaXXXXXXXXXX': 7,
 'A suXXXXXXXXXX': 7,
 'biplXXXXXXXXXX': 7,
 'lineXXXXXXXXXX': 7,
 'raihXXXXXXXXXX': 7,
 'ROBIXXXXXXXXXX': 7,
 's yoXXXXXXXXXX': 7,
 'anbuXXXXXXXXXX': 7,
 'raagXXXXXXXXXX': 7,
 'sendXXXXXXXXXX': 7,
 'r muXXXXXXXXXX': 7,
 'adnaXXXXXXXXXX': 7,
 'saiyXXXXXXXXXX': 7,
 'BALCXXXXXXXXXX': 7,
 'tamiXXXXXXXXXX': 7,
 'beerXXXXXXXXXX': 7,
 'MADAXXXXXXXXXX': 7,
 'J SEXXXXXXXXXX': 7,
 'uddhXXXXXXXXXX': 7,
 'SRITXXXXXXXXXX': 7,
 'ARPIXXXXXXXXXX': 7,
 'SAHAXXXXXXXXXX': 7,
 'saumXXXXXXXXXX': 7,
 'PASAXXXXXXXXXX': 7,
 'subbXXXXXXXXXX': 7,
 'aamaXXXXXXXXXX': 7,
 'HARSXXXXXXXXXX': 7,
 'KESHXXXXXXXXXX': 7,
 'sritXXXXXXXXXX': 7,
 'LALXXXXXXXXXX': 7,
 'kalpXXXXXXXXXX': 7,
 'muttXXXXXXXXXX': 7,
 'UDDHXXXXXXXXXX': 7,
 'KENNXXXXXXXXXX': 7,
 'ede XXXXXXXXXX': 7,
 'ambrXXXXXXXXXX': 7,
 'TARUXXXXXXXXXX': 7,
 'K reXXXXXXXXXX': 6,
 'kanaXXXXXXXXXX': 6,
 'yaraXXXXXXXXXX': 6,
 'sajeXXXXXXXXXX': 6,
 'kencXXXXXXXXXX': 6,
 'A jyXXXXXXXXXX': 6,
 'SANKXXXXXXXXXX': 6,
 'AISHXXXXXXXXXX': 6,
 'DEEKXXXXXXXXXX': 6,
 'LAISXXXXXXXXXX': 6,
 'vipiXXXXXXXXXX': 6,
 'JITEXXXXXXXXXX': 6,
 'dhinXXXXXXXXXX': 6,
 'B PRXXXXXXXXXX': 6,
 'M naXXXXXXXXXX': 6,
 'srihXXXXXXXXXX': 6,
 'mutaXXXXXXXXXX': 6,
 'asitXXXXXXXXXX': 6,
 'BHASXXXXXXXXXX': 6,
 'R KUXXXXXXXXXX': 6,
 'AMALXXXXXXXXXX': 6,
 'rajXXXXXXXXXX': 6,
 'meiyXXXXXXXXXX': 6,
 'AKSHXXXXXXXXXX': 6,
 'CHALXXXXXXXXXX': 6,
 'bhikXXXXXXXXXX': 6,
 'saidXXXXXXXXXX': 6,
 'jugaXXXXXXXXXX': 6,
 'LALAXXXXXXXXXX': 6,
 'swasXXXXXXXXXX': 6,
 'suprXXXXXXXXXX': 6,
 'kausXXXXXXXXXX': 6,
 'amerXXXXXXXXXX': 6,
 'ULIGXXXXXXXXXX': 6,
 'maneXXXXXXXXXX': 6,
 'KUPPXXXXXXXXXX': 6,
 'joshXXXXXXXXXX': 6,
 'SURAXXXXXXXXXX': 6,
 'JAN XXXXXXXXXX': 6,
 'anugXXXXXXXXXX': 6,
 'THIMXXXXXXXXXX': 6,
 'mulaXXXXXXXXXX': 6,
 'a raXXXXXXXXXX': 6,
 'AUGUXXXXXXXXXX': 6,
 'DEBAXXXXXXXXXX': 6,
 'M SUXXXXXXXXXX': 6,
 'MANTXXXXXXXXXX': 6,
 'lithXXXXXXXXXX': 6,
 'G VIXXXXXXXXXX': 6,
 'bifyXXXXXXXXXX': 6,
 'kuldXXXXXXXXXX': 6,
 'N L XXXXXXXXXX': 6,
 'thejXXXXXXXXXX': 6,
 'bivaXXXXXXXXXX': 6,
 'IMRAXXXXXXXXXX': 6,
 'suldXXXXXXXXXX': 6,
 'jackXXXXXXXXXX': 6,
 'K piXXXXXXXXXX': 6,
 'yashXXXXXXXXXX': 6,
 'sohaXXXXXXXXXX': 6,
 'sayeXXXXXXXXXX': 6,
 'JAI XXXXXXXXXX': 6,
 'paneXXXXXXXXXX': 6,
 'aseeXXXXXXXXXX': 5,
 'naroXXXXXXXXXX': 5,
 'D siXXXXXXXXXX': 5,
 'faziXXXXXXXXXX': 5,
 'somuXXXXXXXXXX': 5,
 'S GAXXXXXXXXXX': 5,
 'sricXXXXXXXXXX': 5,
 'duraXXXXXXXXXX': 5,
 'laliXXXXXXXXXX': 5,
 'victXXXXXXXXXX': 5,
 'sreeXXXXXXXXXX': 5,
 'edigXXXXXXXXXX': 5,
 'chalXXXXXXXXXX': 5,
 'DVUNXXXXXXXXXX': 5,
 'rashXXXXXXXXXX': 5,
 'GOWTXXXXXXXXXX': 5,
 'sadaXXXXXXXXXX': 5,
 'ray XXXXXXXXXX': 5,
 'MAGIXXXXXXXXXX': 5,
 'om pXXXXXXXXXX': 5,
 'KANCXXXXXXXXXX': 5,
 'xaviXXXXXXXXXX': 5,
 'PAWAXXXXXXXXXX': 5,
 'pancXXXXXXXXXX': 5,
 'kuraXXXXXXXXXX': 5,
 'KALIXXXXXXXXXX': 5,
 'afaqXXXXXXXXXX': 5,
 'ANMOXXXXXXXXXX': 5,
 'erfaXXXXXXXXXX': 5,
 'YATHXXXXXXXXXX': 5,
 'DODDXXXXXXXXXX': 5,
 'ANIMXXXXXXXXXX': 5,
 'YARAXXXXXXXXXX': 5,
 'gajuXXXXXXXXXX': 5,
 'PRURXXXXXXXXXX': 5,
 'RABAXXXXXXXXXX': 5,
 'pariXXXXXXXXXX': 5,
 'diveXXXXXXXXXX': 5,
 'ramnXXXXXXXXXX': 5,
 'K shXXXXXXXXXX': 5,
 'K maXXXXXXXXXX': 5,
 'bipuXXXXXXXXXX': 5,
 'induXXXXXXXXXX': 5,